version: '3.9'

services:
  alura_flix_api:
    image: "laurocorreia/alura-flix-api:latest"
    container_name: "alura_flix_api"
    networks:
      - compose-brigde
    ports:
      - 8080:8080
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_PRO=${DATABASE_PRO}
networks:
  compose-brigde:
    driver: bridge
