version: '3.9'
services:
  lura_flix_api:
    image: "laurocorreia/alura-flix-api:1.1"
    container_name: "alura_flix_api"
    networks:
      - compose-brigde
    ports:
      - 8080:8080
    env_file:
      - ~/Documents/GitHub/java_challengs_back_end/alura-flix-api/.env
networks:
  compose-brigde:
    driver: bridge