server:
  port: 8080

spring:
  application:
    name: alura-flix-api
  data:
    mongodb:
      database: alura-flix-test
      # always commit the uri like this: ${DATABASE_TEST}
      uri: ${DATABASE_TEST:mongodb+srv://laurosilveira:6Vos5cYJ9JfxidsQ@alura-flix-test.qixe2kd.mongodb.net/?retryWrites=true&w=majority}