server:
  port: 8080
  # Disable StackTrace of Spring on response when an error happen
  error:
    include-stacktrace: never

spring:
  application:
    name: alura-flix-api
  data:
    mongodb:
      database: alura-flix
      # always commit the uri like this: ${DATABASE_PRO}
      uri: ${DATABASE_PRO:mongodb+srv://alura-flix-admin:UxOM6SSAtQHpDeEd@alura-flix.z61opfc.mongodb.net/?retryWrites=true&w=majority}

api:
  security:
    # always commit the uri like this: ${JWT_SECRET}
    token-jwt-secret: ${JWT_SECRET:123456}
