name: Create Release

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Create Release by tag ${GITHUB_REF_NAME#v}
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
        run: |
          gh release create "$GITHUB_REF_NAME" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${GITHUB_REF_NAME#v}" \
              --generate-notes