name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        DATABASE_PRO: ${{ secrets.DATABASE_PRO }}
        DATABASE_TEST: ${{ secrets.DATABASE_TEST }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alura-flix-api:$(date +%s) --build-arg DATABASE_PRO=${{ secrets.DATABASE_PRO }} --build-arg DATABASE_TEST=${{ secrets.DATABASE_TEST }} --build-arg DATABASE_TEST=${{ secrets.DATABASE_TEST }}