name: CI Workflow
run-name: ${{ github.actor }} has startet workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and test with Maven
      run: mvn -B package --file pom.xml
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        DATABASE_PRO: ${{ secrets.DATABASE_PRO }}
        DATABASE_TEST: ${{ secrets.DATABASE_TEST }}

    - name: Create test Summary
      uses: test-summary/action@dist
      with:
        paths: results/**/*.xml
      if: always()